### ISSUE TITLE
Decent/pretty visualization

### ISSUE THREAD

**Issue by bittremieux** [swuyts/lactobot#1]
What kind of visualization do you want?

The bar charts hardly seem the best way to plot this information. First and foremost because right now you're adding a new bar for every new day, so soon the y-axis will become pretty crowded. Second because you can hardly spot where a bar shows an increase compared to the previous day.

If you want to plot the changes over time a simple line plot seems a straightforward choice to me.

**Comment by swuyts** [comment]
Barcharts are definitely the worst choice indeed, but were the easiest for me to implement fast.

I agree, a simple line plot with time on x-axis seems the most straightforward choice.  From my experience in R however, getting dates on the axes will probably be challenging.

**Comment by bittremieux** [comment]
Ha, welcome to the power of Python, a *decent* programming language!
